@startuml

class LessonJsonStructure{
    + lessons: List<LessonClass>
    + version: Long?
    + error: String?
}

class LessonClass{
    + studyroom: String
    + day: Int
    + even: Int
    + group: String
    + lecturer: String
    + number: Int
    + title: String
    + type: Int
    + clear()
    + setFields(LessonClass)
    + isEmpty(): Boolean

}

interface Parcelable{
    + writeToParcel(Parcel, Int)
    + createFromParcel(Parcel): <T>
    + newArray(Int): Array<T>
    + describeContents(): Int
}
interface RealmObject{}


LessonClass --o LessonJsonStructure
LessonClass ..|> Parcelable
LessonClass ..|> RealmObject


@enduml